CREATE TABLE IF NOT EXISTS `api_request_logs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `requestId` VARCHAR(100) NULL,
  `userId` INT UNSIGNED NULL,
  `method` VARCHAR(10) NOT NULL,
  `path` VARCHAR(500) NOT NULL,
  `route` VARCHAR(500) NULL,
  `statusCode` INT UNSIGNED NOT NULL,
  `success` TINYINT(1) NOT NULL,
  `errorCode` VARCHAR(100) NULL,
  `errorMessage` VARCHAR(500) NULL,
  `ip` VARCHAR(100) NULL,
  `userAgent` VARCHAR(500) NULL,
  `requestMeta` JSON NULL,
  `responseMeta` JSON NULL,
  `startedAt` DATETIME NOT NULL,
  `finishedAt` DATETIME NOT NULL,
  `durationMs` INT UNSIGNED NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `api_request_logs_created_idx` (`createdAt`),
  INDEX `api_request_logs_user_created_idx` (`userId`, `createdAt`),
  INDEX `api_request_logs_status_created_idx` (`statusCode`, `createdAt`),
  INDEX `api_request_logs_method_created_idx` (`method`, `createdAt`),
  INDEX `api_request_logs_success_created_idx` (`success`, `createdAt`),
  CONSTRAINT `fk_api_request_logs_user` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
